### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ronenhamias**
introduce Service Fabric IO

### CODE REVIEW

**Comment by mfornos** [comment]
Hi there,
Service-Fabric is already filed under the category `Elastic Computing`.

Many thanks for contributing!

**Comment by ronenhamias** [comment]
it will be good to move it from Elastic Computing

**Comment by mfornos** [comment]
Sure, makes sense.

Please, can you move it to `Runtimes` in this pull request?

Note that the entries under Runtimes are sorted alphabetically and that the description begins with a capital letter (preferably with a noun) and is separated by a dash. 
Like: 
> - [Service Fabric I/O](http://servicefabric.io/) - Framework through which a set of distributed microservices are connected in such as way that they resemble a fabric when viewed collectively.

Thank you so much!

**Comment by ronenhamias** [comment]
thank you for making this project!

**Pull request merged**
